# Copyright 2024 Kinetic Commerce
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Resolve a ref-ish value
description: |
  Resolves a provided open pull request, branch, tag, or commit ref to
  a valid commit reference.

  Ref resolution is always in the order of `pr`, `branch`, `tag`, `commit`,
  `default-branch`, `repo-default-branch`.
author: 'KineticCafe'
inputs:
  token:
    description: |
      The GitHub token for this action.
    required: true
    default: ${{ github.token }}
  ref:
    description: |
      The branch name, open pull request number, tag, or commit reference to
      resolve.

      Pull request numbers must begin with `#` to distinguish them from commits
      that are all decimal digits. Closed or merged pull requests are ignored.

      If `inputs.ref` is omitted or empty, `inputs.default-branch` will be used
      for resolution.
    required: false
  default-branch:
    description: |
      The branch name to use for resolution if `inputs.ref` is omitted or
      empty.

      If `inputs.default-branch` is omitted or empty, this action will look up
      the name of the default branch and use that.
    required: false
  allowed:
    description: |
      The list of ref types that can be resolved. Typically, this will be used
      to restrict `inputs.ref` to open pull requests (with `pr`). This is
      a string containing a comma separated list of ref types. The default is
      `pr,branch,tag,commit`.
    required: false
    default: pr,branch,tag,commit

outputs:
  sha:
    description: The resolved SHA
    value: ${{ steps.resolver.outputs.sha }}
  name:
    description: The name used to resolve the SHA.
    value: ${{ steps.resolver.outputs.name }}
  type:
    description: |
      The type of ref used to resolve the SHA. Will be one of
      `repo-default-branch` (no `ref` or `default-branch` values present),
      `default-branch` (no `ref`, but `default-branch` resolves), `pr` (an open
      PR matched), `branch` (a branch matched), `tag` (a tag matched), or
      `commit` (an explicit commit matched).
    value: ${{ steps.resolver.outputs.type }}

runs:
  using: 'composite'
  steps:
    - id: resolver
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_REF: ${{ inputs.ref }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        ALLOWED: ${{ inputs.allowed || 'pr,branch,tag,commit' }}
      run: '${{ github.action_path }}/resolve-ref.sh'

branding:
  icon: check-circle
  color: blue
