# Copyright 2024 Kinetic Commerce
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Extract a version section from a changelog file
description: |
  Extracts a version section from a changelog file that is similar to [keep
  a changelog](https://keepachangelog.com/).

  Version matching is performed eagerly, so extracting `1.0` will grab the first
  section that matches `1.0`, even if it is `1.0.10`.

author: 'KineticCafe'
inputs:
  version:
    description: |
      The version to extract from the changelog file. The version is treated as
      a plain string.
    required: true
  changelog:
    description: |
      The name of the changelog file to read. Assume that the name is case
      sensitive.
    required: true
  prefix:
    description: |
      The prefix string to use for distinct version detection within the
      changelog. Defaults to `##`, the markdown `h2` header.
    required: true
    default: '##'
  version-pattern:
    description: |
      The version pattern to use. Must be `bare` (`%v`), `bracket` (`[%v]`), or
      a string with `%v` for the location of the version. Defaults to `bare`.

      If your changelog version lines have additional values, such as a build
      number (`[version - build]`), a partial pattern should be used (`[%v -`).
    required: true
    default: 'bare'

outputs:
  contents:
    description: The extracted changelog section.
    value: ${{ steps.extract.outputs.section }}

runs:
  using: 'composite'
  steps:
    - id: extract
      shell: bash
      env:
        INPUT_CHANGELOG: ${{ inputs.changelog }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_PREFIX: ${{ inputs.prefix }}
        INPUT_PATTERN: ${{ inputs.version-pattern }}
      run: |
        ${{ github.action_path }}/extract-changelog.sh

branding:
  icon: align-left
  color: purple
