# Copyright 2023 Kinetic Cafe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Enable Automerge for Dependabot
description: |
  Enables GitHub Automerge for Dependabot PRs
author: KineticCafe

inputs:
  repo-token:
    description: |
      The GitHub token for this action. Requires `pull-requests: write` permission.
    required: true
    default: ${{ github.token }}
  update-type:
    description: |
      The highest level of update that can be automatically merged. The default value is
      `patch`; supported values are `major`, `minor`, and `patch`. Automatic merge for
      `major` is not recommended.
    required: false
    default: patch
  merge-type:
    description: |
      The type of merge to be applied. Defaults to `merge`; supported values are `merge`,
      `rebase`, and `squash`.
    required: false
    default: merge

runs:
  using: 'composite'
  steps:
    - if: >
        (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        && github.actor == 'dependabot[bot]'
      run: echo "UPDATE_TYPE=version-update:semver-${{inputs.update-type}}" >> "${GITHUB_ENV}"
      shell: bash

    - if: >
        (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        && github.actor == 'dependabot[bot]'
      id: metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ inputs.repo-token }}

    - if: >
        (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
        && github.actor == 'dependabot[bot]'
        && steps.metadata.outputs.update-type == env.UPDATE_TYPE
      run: |
        declare merge_flag

        case "${MERGE_TYPE}" in
        merge) merge_flag=--merge ;;
        rebase) merge_flag=--rebase ;;
        squash) merge_flag=--squash ;;
        esac

        gh pr merge --auto "${merge_flag}" "${PR_URL}"
      shell: bash
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        MERGE_TYPE: ${{ inputs.merge-type || 'merge' }}

branding:
  icon: check-circle
  color: blue
