name: Quality Checks

on:
  pull_request:

jobs:
  dco-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: KineticCafe/actions-dco@416cafbc9c07f26219d09981d9ac49ce29b5bfea # v1.3.4
        with:
          exempt-authors: |
            @kineticcommerce.com
            @kineticcafe.com

  dependabot-automerge:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./dependabot-automerge
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          update-type: minor
